### ISSUE TITLE
Umbrella 1.2.0/2.0.0

### ISSUE THREAD

**Issue by frostney** [freezedev/animframe#2]
- [x] Remove udefine (may be a breaking change)
- [x] Transport: CommonJS and AMD (may be a breaking change)
- [x] Use Karma for unit tests

Optional
- [x] ES6 with Babel?

Depending if the first and/or the second item will be a breaking change, it will be either be a SemVer major or minor update.
